FROM ubuntu:22.04
LABEL description "Build zig examples" \
    maintainer="Sazerac4 <lm-embeddedsystems@laposte.net>"

RUN mkdir -vp /opt/bin && mkdir -vp /opt/softs
ENV PATH="/opt/bin:${PATH}"

#Update the image to the latest packages
ARG DEBIAN_FRONTEND=noninteractive
RUN apt update && apt upgrade -y

#Install tools
RUN apt install -y make cmake wget xz-utils

ARG GCC_VERSION="13.2.1-1.1"
ARG ZIG_VERSION="0.13.0"

#Install gcc
RUN cd /tmp && wget https://github.com/xpack-dev-tools/arm-none-eabi-gcc-xpack/releases/download/v${GCC_VERSION}/xpack-arm-none-eabi-gcc-${GCC_VERSION}-linux-x64.tar.gz \
    && tar -xf /tmp/xpack-arm-none-eabi-gcc-*-linux-x64.tar.gz -C /opt/softs/ \
    && ln -s /opt/softs/xpack-arm-none-eabi-gcc-*/bin/arm-none-eabi-*  /opt/bin/

#Install zig
RUN cd /tmp && wget https://ziglang.org/download/${ZIG_VERSION}/zig-linux-x86_64-${ZIG_VERSION}.tar.xz \
    && tar -xf /tmp/zig-linux-x86_64-*.tar.xz -C /opt/softs/ \
    && ln -s /opt/softs/zig-linux-x86_64-*/zig /opt/bin/

#Clean image
RUN apt clean && rm -rf -- /var/lib/apt/lists/* && rm -rf -- /tmp/*

CMD [ "/bin/bash" ]
