FROM debian:12
LABEL description "Build Picolibc" \
    maintainer="Sazerac4 <lm-embeddedsystems@laposte.net>"

ARG DEBIAN_FRONTEND=noninteractive
RUN apt update --fix-missing  && apt upgrade -y

#Install tools
RUN apt install --no-install-recommends -y ca-certificates wget unzip meson ninja-build llvm-19 clang-19 lld-19

#Download picolibc
ARG PICOLIBC_VERSION="1.8.9"
RUN cd /tmp && wget https://github.com/picolibc/picolibc/archive/refs/tags/${PICOLIBC_VERSION}.zip && \
    unzip /tmp/${PICOLIBC_VERSION}.zip && mv /tmp/picolibc-${PICOLIBC_VERSION} /picolibc

#Clean image
RUN apt clean && rm -rf -- /var/lib/apt/lists/* && rm -rf -- /tmp/*

WORKDIR /workspace
VOLUME  /workspace

CMD [ "/bin/bash" ]
