##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [4.3.0-B58] date: [Mon May 20 15:02:45 PDT 2024]
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = blinky_freertos

GCC_VERSION = 13.2.1
GCC_PATH = "/opt/dev/xpack-arm-none-eabi-gcc-13.2.1-1.1/"
GCC_ARCH = "v7e-m+fp"
# You can select clang here if you want
COMPILER = zig cc

######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -Og


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build-zig

######################################
# source
######################################
# C sources
C_SOURCES =  \
Core/Src/main.c \
Core/Src/gpio.c \
Core/Src/usart.c \
Core/Src/stm32l4xx_it.c \
Core/Src/stm32l4xx_hal_msp.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_tim.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_tim_ex.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_rcc.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_rcc_ex.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_flash.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_flash_ex.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_flash_ramfunc.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_gpio.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_i2c.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_i2c_ex.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_dma.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_dma_ex.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_pwr.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_pwr_ex.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_cortex.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_exti.c \
Core/Src/system_stm32l4xx.c \
Core/Src/sysmem.c \
Core/Src/syscalls.c \
Core/Src/freertos-openocd.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_uart.c \
Drivers/STM32L4xx_HAL_Driver/Src/stm32l4xx_hal_uart_ex.c \
Core/Src/freertos.c \
Core/Src/stm32l4xx_hal_timebase_tim.c \
Middlewares/Third_Party/FreeRTOS/Source/croutine.c \
Middlewares/Third_Party/FreeRTOS/Source/event_groups.c \
Middlewares/Third_Party/FreeRTOS/Source/list.c \
Middlewares/Third_Party/FreeRTOS/Source/queue.c \
Middlewares/Third_Party/FreeRTOS/Source/stream_buffer.c \
Middlewares/Third_Party/FreeRTOS/Source/tasks.c \
Middlewares/Third_Party/FreeRTOS/Source/timers.c \
Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/cmsis_os2.c \
Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang/heap_4.c \
Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F/port.c

# ASM sources
ASM_SOURCES =  \
startup_stm32l476xx.s

# ASM sources
ASMM_SOURCES =


#######################################
# binaries
#######################################


# CHANGE NOTE: I'm still using arm-none-eabi-gcc here for size and objcopy utilities, however note that these have no effect on actual compilation

PREFIX = arm-none-eabi-
# CHANGE NOTE: GCC_PATH is required to be defined for our modified makefile to manually grab library paths
#			   There's a more intelligent way to do this but that's an excercise for the reader :)
CP = $(GCC_PATH)/bin/$(PREFIX)objcopy
SZ = $(GCC_PATH)/bin/$(PREFIX)size


# CHANGE NOTE: zig cc is now used in place of arm-none-eabi-gcc
CC = $(COMPILER)
AS = $(COMPILER) -x assembler-with-cpp

HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S

#######################################
# CFLAGS
#######################################
# cpu
# CHANGE NOTE: zig cc uses "_" instead of "-" in -mcpu arg
ifeq ($(COMPILER_PREFIX),clang)
    CPU = -mcpu=cortex-m4 #clang option
else
    CPU = -mcpu=cortex_m4 #zig option
endif


# fpu
FPU = -mfpu=fpv4-sp-d16

# float-abi
FLOAT-ABI = -mfloat-abi=hard
# mcu
# CHANGE NOTE: zig cc requires "--target=thumb-freestanding-eabi" to specify the target for both compilation AND linking
MCU = --target=thumb-freestanding-eabi $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS =

# C defines
C_DEFS =  \
-DUSE_HAL_DRIVER \
-DSTM32L476xx

# AS includes
AS_INCLUDES =

# C includes
C_INCLUDES =  \
-ICore/Inc \
-IDrivers/STM32L4xx_HAL_Driver/Inc \
-IDrivers/STM32L4xx_HAL_Driver/Inc/Legacy \
-IDrivers/CMSIS/Device/ST/STM32L4xx/Include \
-IDrivers/CMSIS/Include \
-IMiddlewares/Third_Party/FreeRTOS/Source/include \
-IMiddlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 \
-IMiddlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F


# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

# CHANGE NOTE: We manually add arm-none-eabi-gcc system headers as a system include path
CFLAGS += -isystem $(GCC_PATH)/arm-none-eabi/include $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = STM32L476RGTx_FLASH.ld

# libraries
# CHANGE NOTE:
#  - Manually provide .a library file locations using "-L" arg
#  - No "-specs=nano.specs" spec sheet exists in zig cc, so we specify the "nano" variant of libc manually ("-lc_nano" instead of "-lc")
#  - "-lgcc" is no longer included, as Zig provides its own equivalent functionality to this library
#  - "-lnosys" is also skipped, as ST already provides code with this functionality, so we get duplicate symbol errors otherwise
LIBS = -lc_nano -lm
LIBDIR = -L$(GCC_PATH)/lib/gcc/arm-none-eabi/$(GCC_VERSION)/thumb/v7e-m+fp/hard/ -L$(GCC_PATH)/arm-none-eabi/lib/thumb/v7e-m+fp/hard/
LDFLAGS = $(MCU) -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,--gc-sections -Wl,--undefined=uxTopUsedPriority

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin


#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))

# CHANGE NOTE: We have to include the c-runtime objects from gcc-arm-none-eabi for our specific architecture
EXTRA_OBJECTS = \
	$(GCC_PATH)/bin/../lib/gcc/arm-none-eabi/$(GCC_VERSION)/thumb/v7e-m+fp/hard/crti.o \
	$(GCC_PATH)/bin/../lib/gcc/arm-none-eabi/$(GCC_VERSION)/thumb/v7e-m+fp/hard/crtbegin.o \
	$(GCC_PATH)/bin/../lib/gcc/arm-none-eabi/$(GCC_VERSION)/thumb/v7e-m+fp/hard/crtn.o \
	$(GCC_PATH)/bin/../lib/gcc/arm-none-eabi/$(GCC_VERSION)/thumb/v7e-m+fp/hard/crtend.o \
	$(GCC_PATH)/bin/../lib/gcc/arm-none-eabi/$(GCC_VERSION)/../../../../arm-none-eabi/lib/thumb/v7e-m+fp/hard/crt0.o

# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASMM_SOURCES:.S=.o)))
vpath %.S $(sort $(dir $(ASMM_SOURCES)))

# CHANGE NOTE: TODO: See if there's a "clang" way of generating assembly files like GCC does with "-Wa,-a,-ad,-alms=..."
$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR)
	$(CC) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/%.o: %.S Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

# CHANGE NOTE: $(MCU) args have been added here since zig's linker (LLVM's ld.lld) requires them
$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CC) $(MCU) $(OBJECTS) $(EXTRA_OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@

$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@

$(BUILD_DIR):
	mkdir $@

#######################################
# clean up
#######################################
clean:
	-rm -fR $(BUILD_DIR)

#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

# *** EOF ***
